[package]
name = "hop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colored = "2"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
dirs = "6.0.0"
